Cubes.Web/Models/Publication.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cubes.Web.Models
{
    public class Publication
    {
        //[Key]
        public int IdPublication { get; set; }

        public string Titre { get; set; }

        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
}

Cubes.Web/Models/Ressource.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cubes.Web.Models
{
    public class Ressource
    {
        [Key]
        public int IdRessource { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [StringLength(50, ErrorMessage = "Ce champ doit contenir au maximum {1} caractères et au minimum {2}", MinimumLength = 3)]
        [Display(Name = "Nom")]
        public string Nom { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [Display(Name = "Catégorie ressource")]
        public int IdCategorie { get; set; }

        [Display(Name = "Créee par")]
        public string User { get; set; }

        //[Required(ErrorMessage = "Ce champ est obligatoire")]
        [StringLength(50, ErrorMessage = "Ce champ doit contenir au maximum {1} caractères et au minimum {2}", MinimumLength = 3)]
        [Display(Name = "Titre")]
        [ScaffoldColumn(false)]
        public string Titre { get; set; }

        [Display(Name = "Est public")]
        public bool IsPrivate { get; set; }

        [Display(Name = "A été validée")]
        public bool IsValid { get; set; }

        [Display(Name = "A été publiée")]
        public bool IsPublish { get; set; }

        [Display(Name = "Est favorite")]
        public bool IsFavorite { get; set; }

        [Display(Name = "Est exploitable")]
        public bool IsOperate { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date de création")]
        [ScaffoldColumn(false)]
        public DateTime? DateCreation { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd hh:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date de publication")]
        [ScaffoldColumn(false)]
        public DateTime? DatePublication { get; set; }

        [StringLength(200, ErrorMessage = "Ce champ doit contenir au maximum {1} caractères et au minimum {2}", MinimumLength = 5)]
        [Display(Name = "Joindre fichier")]
        public string Fichier { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        public string fichierFullPath => string.IsNullOrEmpty(Fichier)
            ? null
            : $"http://prolink.somee.com{Fichier.Substring(1)}";

        public virtual Categorie Categorie { get; set; }

        public ICollection<Commentaire> Commentaires { get; set; }
    }
}

Cubes.Web/Models/RessourceView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Cubes.Web.Models
{
    [NotMapped]
    public class RessourceView : Ressource
    {
        public HttpPostedFileBase FichierFile { get; set; }
    }
}

Cubes.Web/Controllers/PublicationsController.cs
using Cubes.Web.Models;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Cubes.Web.Controllers
{
    [Authorize]
    public class PublicationsController : Controller
    {
        private DataContext db = new DataContext();

        // Liste des publications
        public async Task<ActionResult> Index()
        {
            var ressources = db.Ressources.Where(r => r.IsPublish == true)
                                          .Where(r => r.IsValid == true)
                                          .Include(r => r.Categorie);
            return View(await ressources.OrderBy(r => r.DatePublication).ToListAsync());
        }
    }
}

Cubes.Web/Controllers/RessourcesController.cs
using System.Data.Entity;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Cubes.Web.Models;
using System.Linq;
using Cubes.Web.Helpers;
using System;

namespace Cubes.Web.Controllers
{
    public class RessourcesController : Controller
    {
        private DataContext db = new DataContext();

        // Poster un commentaire
        public async Task<ActionResult> PostComment(CommentView view)
        {
            // On récupère la séssion de l'utilisateur connecté
            int idUser = Convert.ToInt32(Session["IdUser"]);
            if (idUser == 0)
            {
                return RedirectToAction("Login", "Account");
            }

            Commentaire c = new Commentaire();
            c.Text = view.CommentText;
            c.IdUser = idUser;
            c.IdRessource = view.IdRessource;
            c.DateCommentaire = DateTime.Now;

            db.Commentaires.Add(c);
            await db.SaveChangesAsync();

            return RedirectToAction($"{nameof(Publications)}");
        }

        // Liste des publications public
        public async Task<ActionResult> Publications(string search)
        {
            var ressources = db.Ressources.Where(r => r.IsPublish == true)
                                          .Where(r => r.IsValid == true)
                                          .Where(r => r.IsPrivate == true)
                                          .Include(r => r.Categorie)
                                          .Include(m => m.Commentaires);



            //var ressources = from r in db.Ressources
            //                 select r;

            if (!String.IsNullOrEmpty(search))
            {
                ressources = ressources.Where(r => r.Categorie.Libelle.Contains(search));
            }

            return View(await ressources.OrderByDescending(r => r.DatePublication).ToListAsync());
        }

        // Liste des publications public
        //public async Task<ActionResult> Publications()
        //{
        //    var ressources = db.Ressources.Where(r => r.IsPublish == true)
        //                                  .Where(r => r.IsValid == true)
        //                                  .Where(r => r.IsPrivate == true)
        //                                  .Include(r => r.Categorie);
        //    return View(await ressources.OrderByDescending(r => r.DatePublication).ToListAsync());
        //}

        // Liste des publications public
        //[Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        //public async Task<ActionResult> MyPublish()
        //{

        //    var ressources = await db.Ressources.Where(r => r.IsPublish == true)
        //                                  .Where(r => r.IsValid == true)
        //                                  .Where(r => r.IsPrivate == true)
        //                                  .Where(r => r.User == )
        //                                  .Include(r => r.Categorie)
        //                                  .OrderBy(r => r.DatePublication).ToListAsync();
        //    return View(ressources);
        //}

        // Publier la ressource
        [Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        public async Task<ActionResult> Publish(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ressource ressource = await db.Ressources.FindAsync(id);

            if(ressource != null)
            {
                if(ressource.IsPublish == false)
                {
                    ressource.IsPublish = true;
                    ressource.DatePublication = DateTime.Now;
                    ressource.IsPrivate = true;

                    db.Entry(ressource).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index");
        }

        // Valider une ressource pour publication
        [Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        public async Task<ActionResult> Validate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ressource ressource = await db.Ressources.FindAsync(id);

            if (ressource != null)
            {
                if (ressource.IsPublish == true && ressource.IsPrivate == true)
                {
                    ressource.IsValid = true;

                    db.Entry(ressource).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index");
        }

        // Suspendre ressource
        [Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        public async Task<ActionResult> Suspendre(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ressource ressource = await db.Ressources.FindAsync(id);

            if (ressource != null)
            {
                if (ressource.IsPublish == true && ressource.IsPrivate == true)
                {
                    ressource.IsValid = false;

                    db.Entry(ressource).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index");
        }

        // Changer photo utilisateur
        [Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        public async Task<ActionResult> ChangeFile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ressource ressource = await db.Ressources.FindAsync(id);
            if (ressource == null)
            {
                return HttpNotFound();
            }

            var view = new RessourceFileView
            {
                IdRessource = ressource.IdRessource,
                IdCategorie = ressource.IdCategorie,
                Nom = ressource.Nom,
                IsPrivate = ressource.IsPrivate,
                Titre = ressource.Titre,
                Description = ressource.Description,
                Fichier = ressource.Fichier,
            };

            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Libelle", ressource.IdCategorie);
            return View(view);
        }


        // Changer photo utilisateur
        [HttpPost]
        public async Task<ActionResult> ChangeFile(RessourceFileView view)
        {
            var file = string.Empty;
            var folder = "~/Content/Files";

            // Charger la photo
            if (view.NewFile != null)
            {
                file = FilesHelper.UploadFile(view.NewFile, folder);
                file = string.Format("{0}/{1}", folder, file);
            }
            else
            {
                file = "~/Content/Files/noimage.png";
            }

            var ressource = new Ressource
            {

                IdRessource = view.IdRessource,
                IdCategorie = view.IdCategorie,
                Nom = view.Nom,
                IsPrivate = view.IsPrivate,
                Titre = view.Titre,
                Description = view.Description,
                Fichier = view.Fichier,
            };

            ressource.Fichier = file;
            db.Entry(ressource).State = EntityState.Modified;
            await db.SaveChangesAsync();

            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Libelle", ressource.IdCategorie);
            return RedirectToAction($"{nameof(Details)}/{ressource.IdRessource}");
        }

        // Liste des ressources
        public async Task<ActionResult> Index()
        {
            var ressources = db.Ressources.Include(r => r.Categorie);
            return View(await ressources.OrderBy(r => r.Nom).ToListAsync());
        }

        // GET: Ressources/Details/5
        [Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Ressource ressource = await db.Ressources.FindAsync(id);
            if (ressource == null)
            {
                return HttpNotFound();
            }

            var ressourceView = ToView(ressource);

            ViewBag.IdCategorie = new SelectList(db.Categories, "IdCategorie", "Libelle", ressource.IdCategorie);
            return View(ressourceView);
        }

        // Créer ressource / GET
        [Authorize(Roles = "SuperAdmin, Admin, Moderateur, Citoyen")]
        public ActionResult Create()
        {
            ViewBag.IdCategorie = new SelectList(db.Categories.OrderBy(c => c.Libelle), "IdCategorie", "Libelle");
            return View();
        }

        // Créer ressource / POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RessourceView ressourceView)
        {
            if (ModelState.IsValid)
            {
                var file = string.Empty;
                var folder = "~/Content/Files";

                // Charger le fichier
                if (ressourceView.FichierFile != null && ressourceView.FichierFile.ContentLength < 104857600)
                {
                    file = FilesHelper.UploadFile(ressourceView.FichierFile, folder);
                    file = string.Format("{0}/{1}", folder, file);
                }
                else
                {
                    file = "~/Content/Files/noimage.png";
                }

                // On trouve l'utilisateur connecté
                var emailUser = this.User.Identity.Name;

Cubes.Web/Views/Ressources/ChangeFile.cshtml
@model Cubes.Web.Models.RessourceFileView

@{
    ViewBag.Title = "Détails ressource";
}

<br />
<h3 class="text-center">Joindre un autre fichier</h3>


@using (Html.BeginForm("ChangeFile", "Ressources", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdRessource)

        <br />
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdCategorie, "Catégorie", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("IdCategorie", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        @Html.ActionLink("Revenir à l'accueil", "Index", "Ressources", new { }, new { @class = "btn btn-warning" })
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                @if (!string.IsNullOrEmpty(Model.Fichier))
                {
                    if (Model.Fichier.Contains(".jpg") || Model.Fichier.Contains(".png") || Model.Fichier.Contains(".gif") || Model.Fichier.Contains(".tiff"))
                    {
                        <img src="@Url.Content(Model.Fichier)" alt="Fichier joint" style="width:350px;height:350px;max-width: 100%; height: auto;" />
                    }
                    else if (Model.Fichier.Contains(".mp4"))
                    {
                        <div class="video-frame">
                            <video style="width:350px; height:350px" controls>
                                <source src="@Url.Content(Model.Fichier)" type="video/mp4" au autstart="true" loop="false" runat="server" style="border: gray 1px solid" />
                            </video>
                        </div>
                    }
                    else if (Model.Fichier.Contains(".avi"))
                    {
                        <div class="video-frame">
                            <video style="width:350px; height:350px" controls>
                                <source src="@Url.Content(Model.Fichier)" type="video/avi" autstart="true" loop="false" runat="server" style="border: gray 1px solid" />
                            </video>
                        </div>
                    }
                    else if (Model.Fichier.Contains(".webm"))
                    {
                        <div class="video-frame">
                            <video style="width:350px; height:350px" controls>
                                <source src="@Url.Content(Model.Fichier)" type="video/webm" autstart="true" loop="false" runat="server" style="border: gray 1px solid" />
                            </video>
                        </div>
                    }
                    else if (Model.Fichier.Contains(".mp3"))
                    {
                        <div class="audio-frame">
                            <audio style="width:350px; height:350px" controls>
                                <source src="@Url.Content(Model.Fichier)" type="audio/mp3" autstart="true" loop="false" runat="server" style="border: gray 1px solid" />
                            </audio>
                        </div>
                    }
                    else if (Model.Fichier.Contains(".aac"))
                    {
                        <div class="audio-frame">
                            <audio style="width:350px; height:350px" controls>
                                <source src="@Url.Content(Model.Fichier)" type="audio/aac" autstart="true" loop="false" runat="server" style="border: gray 1px solid" />
                            </audio>
                        </div>
                    }
                    else if (Model.Fichier.Contains(".mp4"))
                    {
                        <div class="audio-frame">
                            <audio style="width:350px; height:350px" controls>
                                <source src="@Url.Content(Model.Fichier)" type="audio/mp4" autstart="true" loop="false" runat="server" style="border: gray 1px solid" />
                            </audio>
                        </div>
                    }
                    else if (Model.Fichier.Contains(".pdf"))
                    {
                        <p style="width:350px;height:350px;"><a href="@Url.Content(Model.Fichier)" target="_blank"><img src="~/Content/Files/icons8-pdf-100.png" />Ouvrir le fichier</a></p>
                        @*<p style="width:350px;height:350px;"><a href="@Url.Content(Model.Fichier)" target="_blank"><img src="~/Content/Files/icons8-pdf.png" /></a></p>*@
                    }
                    else if (Model.Fichier.Contains(".docx"))
                    {
                        <p style="width:350px;height:350px;"><a href="@Url.Content(Model.Fichier)" target="_blank"><img src="~/Content/Files/icons8-microsoft-word-2019-240.png" />Ouvrir le fichier</a></p>
                    }
                    else if (Model.Fichier.Contains(".xls") || Model.Fichier.Contains(".xlsx"))
                    {
                        <p style="width:350px;height:350px;"><a href="@Url.Content(Model.Fichier)" target="_blank"><img src="~/Content/Files/icons8-microsoft-excel-2019-240.png" />Ouvrir le fichier</a></p>
                    }
                    else if (Model.Fichier.Contains(".pptx"))
                    {
                        <p style="width:350px;height:350px;"><a href="@Url.Content(Model.Fichier)" target="_blank"><img src="~/Content/Files/icons8-microsoft-powerpoint-2019-240.png" />Ouvrir le fichier</a></p>
                    }
                }

                <div class="form-group">
                    <div class="col-md-10">
                        <span class="btn btn-default btn-file">
                            @Html.TextBoxFor(modele => modele.NewFile, new { type = "file" })
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Enregistrer" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cubes.Web/Views/Ressources/Create.cshtml
@model Cubes.Web.Models.RessourceView

@{
    ViewBag.Title = "Création ressource";
}

<h2 class="text-center">Créer une nouvelle ressource</h2>
<h4 class="alert-danger">@ViewBag.Error</h4>

<br />
<br />
@using (Html.BeginForm("Create", "Ressources", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCategorie, "Catégorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCategorie", null, "Sélectionnez la catégorie de la ressource", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.IsPrivate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsPrivate)
                        @Html.ValidationMessageFor(model => model.IsPrivate, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsValid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsValid)
                        @Html.ValidationMessageFor(model => model.IsValid, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsPublish, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsPublish)
                        @Html.ValidationMessageFor(model => model.IsPublish, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsFavorite, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsFavorite)
                        @Html.ValidationMessageFor(model => model.IsFavorite, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Fichier, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="btn btn-default btn-file">
                    @Html.TextBoxFor(modele => modele.FichierFile, new { type = "file" })
                </span>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Créer" class="btn btn-primary" />
                @Html.ActionLink("Revenir à la liste", "Index", new { }, new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cubes.Web/Views/Ressources/Delete.cshtml
@model Cubes.Web.Models.Ressource

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ressource</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Categorie.Libelle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie.Libelle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPrivate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPrivate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsValid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsValid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPublish)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPublish)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsFavorite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsFavorite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOperate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOperate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fichier)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fichier)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>