Cubes.Web/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Cubes.Web.Models
{
    public class Message
    {
        [Key]
        public int IdMessage { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        [Display(Name = "Entrez votre méssage")]
        public string Text { get; set; }

        [ScaffoldColumn(false)]
        public DateTime? DateEnvoie { get; set; }

        public int IdUser { get; set; }

        [ForeignKey("IdUser")]
        public virtual User User { get; set; }

        public ICollection<Reply> Replies { get; set; }
    }
}

Cubes.Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Cubes.Web.Models;

namespace Cubes.Web.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private DataContext db = new DataContext();

        // GET: Messages
        public async Task<ActionResult> Index()
        {
            var messages = await db.Messages.Include(m => m.Replies)
                                            .OrderByDescending(m => m.DateEnvoie).ToListAsync();
            return View(messages);
        }

        // Poster un commentaire
        public async Task<ActionResult> PosterMessage(string MessageText)
        {
            // On récupère la séssion de l'utilisateur connecté
            int idUser = Convert.ToInt32(Session["IdUser"]);
            if (idUser == 0)
            {
                return RedirectToAction("Login", "Account");
            }

            Message m = new Message();
            m.Text = MessageText;
            m.IdUser = idUser;
            m.DateEnvoie = DateTime.Now;

            db.Messages.Add(m);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // Poster une réponse 
        public async Task<ActionResult> PosterReponse(ReplyView view)
        {
            // On récupère la séssion de l'utilisateur connecté
            int idUser = Convert.ToInt32(Session["IdUser"]);
            if(idUser == 0)
            {
                return RedirectToAction("Login", "Account");
            }

            Reply r = new Reply();
            r.Text = view.Reply;
            r.IdMessage = view.IdMessage;
            r.IdUser = idUser;
            r.DateReponse = DateTime.Now;

            db.Replies.Add(r);
            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        //// GET: Messages/Details/5
        //public async Task<ActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Message message = await db.Messages.FindAsync(id);
        //    if (message == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(message);
        //}

        //// GET: Messages/Create
        //public ActionResult Create()
        //{
        //    ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Email");
        //    return View();
        //}

        //// POST: Messages/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "IdMessage,Text,DateEnvoie,IdUser")] Message message)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Messages.Add(message);
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Email", message.IdUser);
        //    return View(message);
        //}

        //// GET: Messages/Edit/5
        //public async Task<ActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Message message = await db.Messages.FindAsync(id);
        //    if (message == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Email", message.IdUser);
        //    return View(message);
        //}

        //// POST: Messages/Edit/5
        //// To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //// more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Edit([Bind(Include = "IdMessage,Text,DateEnvoie,IdUser")] Message message)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(message).State = EntityState.Modified;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.IdUser = new SelectList(db.Users, "IdUser", "Email", message.IdUser);
        //    return View(message);
        //}

        //// GET: Messages/Delete/5
        //public async Task<ActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Message message = await db.Messages.FindAsync(id);
        //    if (message == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(message);
        //}

        //// POST: Messages/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> DeleteConfirmed(int id)
        //{
        //    Message message = await db.Messages.FindAsync(id);
        //    db.Messages.Remove(message);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Cubes.Web/Views/Messages/Create.cshtml
@model Cubes.Web.Models.Message

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.IdUser, "IdUser", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdUser", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdUser, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cubes.Web/Views/Messages/Delete.cshtml
@model Cubes.Web.Models.Message

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Cubes.Web/Views/Messages/Details.cshtml
@model Cubes.Web.Models.Message

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Message</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IdMessage }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Cubes.Web/Views/Messages/Edit.cshtml
@model Cubes.Web.Models.Message

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Message</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdMessage)

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdUser, "IdUser", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdUser", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdUser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Cubes.Web/Views/Messages/Index.cshtml
@model IEnumerable<Cubes.Web.Models.Message>

@{
    ViewBag.Title = "Chat";
}

<h2 class="text-center text-success">Bienvenue sur la discussion !</h2>
@using (Html.BeginForm("PosterMessage", "Messages", FormMethod.Post))
{
    <input class="pull-right" type="text" name="MessageText" placeholder="Ecriver un commentaire..." style="width: 700px; height: 60px; font-size: 20px; margin-top: 10px" />
    <br /><br /><br /><br />
    <input type="submit" value="Poster" class="btn btn-success pull-right" style="margin-bottom: 10px" />
}

<table class="table text-center">

    @foreach (var message in Model)
    {
        <tr style="border:1px solid black">
            <td>
                <div class="pull-right">
                    <span style="margin-right:15px; font-size:16px; color:green">
                        <img src="@Url.Content(message.User.Photo)" class="img-circle" alt="Photo de l'utiliisateur" style="width:30px;height:30px;max-width: 100%; height: auto;" />
                        @message.User.NomComplet
                    </span>
                    <span style="margin-left:10px">
                        @message.DateEnvoie
                    </span>
                    <span style="font-size:20px">
                        @Html.DisplayFor(modelItem => message.Text)
                    </span>
                </div>
                @foreach (var reply in message.Replies)
                {
                    <br />
                    <div class="pull-left">
                        <span style="margin-right:15px; font-size:16px; color:blueviolet">
                            <img src="@Url.Content(reply.User.Photo)" class="img-circle" alt="Photo de l'utiliisateur" style="width:30px;height:30px;max-width: 100%; height: auto;" />
                            @reply.User.NomComplet
                        </span>
                        <span style="margin-left:10px">
                            @reply.DateReponse
                        </span>
                        <span style="font-size:19px">
                            @reply.Text
                        </span>
                    </div>
                }
                @using (Html.BeginForm("PosterReponse", "Messages", FormMethod.Post))
                {
                    <br /><br /><br /><br />
                    <div class="pull-left">
                        <input type="text" name="Reply" placeholder="Entrez une réponse..." style="width: 100%; height: 70px; font-size: 20px; margin-top: 10px" />
                        <br />
                        <input type="hidden" name="IdMessage" value="@message.IdMessage" />
                        <input type="submit" value="Répondre" class="btn btn-success" style="margin-top: 10px" />
                    </div>
                }
            </td>
        </tr>
    }

</table>